apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default .Release.Name .Values.name }}
  namespace: {{ default .Release.Namespace .Values.name }}
  {{- if or
    .Values.alb
    .Values.extraAnnotations
  }}
  annotations:
    {{- if .Values.alb -}}
    {{- .Values.alb | include "toAlbAnnotations" }}
    {{- end -}}
    {{- if .Values.extraAnnotations -}}
    {{- .Values.extraAnnotations | toYaml | nindent 4}}
    {{- end -}}
  {{- end }}
spec:
  {{- .Values.spec | toYaml | nindent 2 }}